const items = [
  {
    id: 1,
    title: 'Sass',
    description: 'Sass is the most mature, stable, and powerful professional grade CSS extension language in the world.',
    url: 'https://sass-lang.com/',
    votes: 75,
    icon: 'DiSass',
    iconLibrary: 'di',
  },
  {
    id: 2,
    title: 'Tailwind CSS',
    description: 'A utility-first CSS framework packed with classes like flex, pt-4, text-center and rotate-90 that can be composed to build any design, directly in your markup.',
    url: 'https://tailwindcss.com/',
    votes: 85,
    icon: 'SiTailwindcss',
    iconLibrary: 'si',
  },
  {
    id: 3,
    title: 'WordPress',
    description: 'The world\'s most popular website builder.',
    url: 'https://wordpress.com/',
    votes: 90,
    icon: 'DiWordpress',
    iconLibrary: 'di',
  },
  {
    id: 4,
    title: 'React.js',
    description: 'A JavaScript library for building user interfaces.',
    url: 'https://reactjs.org/',
    votes: 30,
    icon: 'DiReact',
    iconLibrary: 'di',
  },
  {
    id: 5,
    title: 'Laravel',
    description: 'Laravel is a web application framework with expressive, elegant syntax.',
    url: 'https://laravel.com/',
    votes: 35,
    icon: 'DiLaravel',
    iconLibrary: 'di',
  },
  {
    id: 6,
    title: 'Vue.js',
    description: 'An approachable, performant and versatile framework for building web user interfaces.',
    url: 'https://vuejs.org/',
    votes: 40,
    icon: 'SiVuedotjs',
    iconLibrary: 'si',
  },
  {
    id: 7,
    title: 'webpack',
    description: 'A static module bundler for modern JavaScript applications.',
    url: 'https://webpack.js.org/',
    votes: 65,
    icon: 'SiWebpack',
    iconLibrary: 'si',
  },
  {
    id: 8,
    title: 'Github',
    description: 'A code hosting platform for version control and collaboration.',
    url: 'https://github.com/',
    votes: 60,
    icon: 'SiGithub',
    iconLibrary: 'si',
  },
  {
    id: 9,
    title: 'Shopify',
    description: 'One platform with all the ecommerce and point of sale features you need to start, run, and grow your business.',
    url: 'https://www.shopify.com/',
    votes: 25,
    icon: 'SiShopify',
    iconLibrary: 'si',
  },
  {
    id: 10,
    title: 'Netlify',
    description: 'Netlify unites an entire ecosystem of modern tools and services into a single, simple workflow for building high performance sites and apps.',
    url: 'https://www.netlify.com/',
    votes: 35,
    icon: 'SiNetlify',
    iconLibrary: 'si',
  },
  {
    id: 11,
    title: 'GraphQL',
    description: 'A query language for your API.',
    url: 'https://graphql.org/',
    votes: 40,
    icon: 'SiGraphql',
    iconLibrary: 'si',
  },
  {
    id: 12,
    title: 'Gridsome',
    description: 'Gridsome makes it easy for developers to build static generated websites & apps that are fast by default.',
    url: 'https://gridsome.org/',
    votes: 40,
    icon: 'SiGridsome',
    iconLibrary: 'si',
  },
  {
    id: 13,
    title: 'Bootstrap',
    description: 'The world\'s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.',
    url: 'https://getbootstrap.com/',
    votes: 75,
    icon: 'SiBootstrap',
    iconLibrary: 'si',
  }
];

const data = {
  items: items
}

export default data;